# Generated by Django 4.2.6 on 2023-10-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe_db", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hop",
            name="pairings",
            field=models.ManyToManyField(related_name="paired_with_list", to="recipe_db.hop"),
        ),
        migrations.AlterField(
            model_name="hop",
            name="substitutes",
            field=models.ManyToManyField(related_name="substitute_for_list", to="recipe_db.hop"),
        ),
    ]
