# Generated by Django 4.2.6 on 2023-10-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe_db", "0002_hop_pairings_alter_hop_substitutes"),
    ]

    operations = [
        migrations.CreateModel(
            name="IgnoredHop",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
