# Generated by Django 4.2.6 on 2023-11-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe_db", "0003_ignoredhop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fermentable",
            name="alt_names_extra",
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="hop",
            name="alt_names_extra",
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="style",
            name="alt_names_extra",
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="yeast",
            name="alt_names_extra",
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
    ]
