# Generated by Django 4.2.6 on 2023-11-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe_db", "0004_alter_fermentable_alt_names_extra_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_id", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=128)),
                ("icon", models.CharField(blank=True, default=None, max_length=10240, null=True)),
                ("page_url", models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ("recipe_url", models.CharField(blank=True, default=None, max_length=1024, null=True)),
            ],
        ),
    ]
