# Generated by Django 4.2.6 on 2023-11-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe_db", "0005_sourceinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="associated_fermentables",
            field=models.ManyToManyField(related_name="all_recipes", to="recipe_db.fermentable"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="associated_hops",
            field=models.ManyToManyField(related_name="all_recipes", to="recipe_db.hop"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="associated_yeasts",
            field=models.ManyToManyField(related_name="all_recipes", to="recipe_db.yeast"),
        ),
    ]
