# Generated by Django 4.2.6 on 2023-11-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe_db", "0006_recipe_associated_fermentables_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["ibu"], name="recipe_db_r_ibu_059edb_idx"),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["abv"], name="recipe_db_r_abv_3a84da_idx"),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["og"], name="recipe_db_r_og_290b98_idx"),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["srm"], name="recipe_db_r_srm_e6676b_idx"),
        ),
    ]
