# Generated by Django 4.2.6 on 2023-11-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe_db", "0007_recipe_recipe_db_r_ibu_059edb_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["created"], name="recipe_db_r_created_b37299_idx"),
        ),
    ]
