# Generated by Django 4.2.6 on 2023-12-10 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recipe_db", "0009_fermentable_search_popularity_hop_search_popularity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hop",
            name="pairings",
        ),
        migrations.CreateModel(
            name="HopPairing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rank", models.IntegerField()),
                ("hop", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="recipe_db.hop")),
                (
                    "paired_hop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="pairedhop_set", to="recipe_db.hop"
                    ),
                ),
            ],
        ),
    ]
