# Generated by Django 4.2.6 on 2024-01-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe_db", "0010_remove_hop_pairings_hoppairing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="style",
            name="bitter_balances",
        ),
        migrations.RemoveField(
            model_name="style",
            name="color",
        ),
        migrations.RemoveField(
            model_name="style",
            name="conditioning",
        ),
        migrations.RemoveField(
            model_name="style",
            name="era",
        ),
        migrations.RemoveField(
            model_name="style",
            name="family",
        ),
        migrations.RemoveField(
            model_name="style",
            name="fermentation",
        ),
        migrations.RemoveField(
            model_name="style",
            name="region_of_origin",
        ),
        migrations.RemoveField(
            model_name="style",
            name="smoke_roast",
        ),
        migrations.RemoveField(
            model_name="style",
            name="sour_hoppy_sweet",
        ),
        migrations.RemoveField(
            model_name="style",
            name="specialty_beer",
        ),
        migrations.RemoveField(
            model_name="style",
            name="spice",
        ),
        migrations.RemoveField(
            model_name="style",
            name="strength",
        ),
        migrations.AlterField(
            model_name="style",
            name="id",
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
