# Generated by Django 4.2.9 on 2024-01-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe_db", "0012_style_bjcp_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="style_oor",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
