version: 2
updates:
    -   package-ecosystem: "pip"
        directory: "/"
        schedule:
            interval: "weekly"
        assignees:
            - "scheb"
    -   package-ecosystem: "npm"
        directory: "/"
        schedule:
            interval: "weekly"
        assignees:
            - "scheb"
