version: '3.8'

services:

    django:
        build:
            context: .
            dockerfile: ./build/local/Dockerfile
        image: beer_analytics_local
        container_name: beer_analytics_django
        restart: on-failure
        environment:
            DATABASE_HOST: beer_analytics_db
            DATABASE_NAME: beer_analytics
            DATABASE_USER: root
            DATABASE_PASSWORD: root
            SECRET_KEY: ${SECRET_KEY}
            RAW_DATA_DIR: ${RAW_DATA_DIR}
            CACHE_DIR: ${CACHE_DIR}
            ALLOWED_HOSTS: ${ALLOWED_HOSTS}
            LOG_FILE: ${LOG_FILE}
            LOG_LEVEL: ${LOG_LEVEL}
            WEB_ANALYTICS_ROOT_URL: '/wa/'
            WEB_ANALYTICS_SITE_ID: 0
            GOOGLE_API_CLIENT_CONFIG_FILE: ${GOOGLE_API_CLIENT_CONFIG_FILE}
            OPENAI_API_KEY: ${OPENAI_API_KEY}
        volumes:
            - .:/app:z
        ports:
            - "8000:8000"
        depends_on:
            - db

    db:
        image: mariadb:11.0
        container_name: beer_analytics_db
        environment:
            MARIADB_DATABASE: beer_analytics
            MARIADB_USER: beer_analytics
            MARIADB_PASSWORD: beer_analytics
            MARIADB_ROOT_PASSWORD: 'root'
            MARIADB_AUTO_UPGRADE: 1
        ports:
            - "3308:3306"
        volumes:
            - 'beer_analytics_db:/var/lib/mysql'

volumes:
    beer_analytics_db:
