version: '3.8'

services:

    django:
        build:
            context: .
            dockerfile: ./build/local/Dockerfile
        image: beer_analytics_local
        container_name: beer_analytics_django
        restart: on-failure
        environment:
            OPENAI_API_KEY: ${OPENAI_API_KEY}
        volumes:
            - .:/app:z
        ports:
            - "8000:8000"
        depends_on:
            - db

    db:
        env_file:
            - config/.env
        image: mariadb:11.0
        container_name: beer_analytics_db
        environment:
            MARIADB_DATABASE: ${DATABASE_NAME}
            MARIADB_USER: ${DATABASE_USER}
            MARIADB_PASSWORD: ${DATABASE_PASSWORD}
            MARIADB_ROOT_PASSWORD: 'root'
            MARIADB_AUTO_UPGRADE: 1
        ports:
            - "3308:3306"
        volumes:
            - 'beer_analytics_db:/var/lib/mysql'

volumes:
    beer_analytics_db:
