version: '3.8'

services:

    django:
        build:
            context: .
            dockerfile: ./build/local/Dockerfile
        image: beer_analytics_local
        container_name: beer_analytics_django
        restart: on-failure
        volumes:
            - .:/app:z
        ports:
            - "8000:8000"
        depends_on:
            - db

    db:
        env_file:
            - beer_analytics/.env
        image: mysql:8.0
        container_name: beer_analytics_db
        environment:
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - "3308:3306"
        volumes:
            - 'beer_analytics_db:/var/lib/mysql'

volumes:
    beer_analytics_db:
